version: '3.9'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - my_network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CREATE_TOPICS: "reservations:1:1"
    depends_on:
      - zookeeper
    networks:
      - my_network

  db:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - my_network

  kafka-consumer:
    build: .
    command: python -m setup.audit_service_runner
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
    networks:
      - my_network

  fastapi:
    build: .
    depends_on:
      - kafka
      - db
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
    ports:
      - "8000:8000"
    networks:
      - my_network

  test:
    build: .
    command: pytest -vv
    depends_on:
      - fastapi
      - kafka
      - db
      - kafka-consumer
    

networks:
  my_network:
    driver: bridge
